# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
version: "3"
services:
  mo_ldap_import_export:
    environment:
      DAP__ENABLED: "true"
    ports:
      - "5678:5678"
